<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="en" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
	<!--1column.phtml-->
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col1-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
		<div id="custom_block2"><?php echo $this->getChildHtml('custom_block2') ?></div>
        <div id="custom_block3"><?php echo $this->getChildHtml('custom_block3') ?></div>
        <div id="custom_block4"><?php echo $this->getChildHtml('custom_block4') ?></div>
        <div id="custom_block5"><?php echo $this->getChildHtml('custom_block5') ?></div>
        <div id="custom_block6"><?php echo $this->getChildHtml('custom_block6') ?></div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>


<!-- 
<link rel="stylesheet" type="text/css" href="http://a.balajeecreation.in/Advertising-Delhi-Css/elastislide.css" />
<script type="text/javascript" src="http://a.balajeecreation.in/Advertising-Delhi-JavaScript/modernizr.custom.17475.js"></script>
<script type="text/javascript" src="http://a.balajeecreation.in/Advertising-Delhi-JavaScript/jquerypp.custom.js"></script>
<script type="text/javascript" src="http://a.balajeecreation.in/Advertising-Delhi-JavaScript/jquery.elastislide.js"></script>
<script type="text/javascript">			$( '#carousel' ).elastislide();		</script>
-->

<!-- 
<script src="http://demo.balajeecreation.in/anim-apr14/greenKI-canvasBg/animatedbg.js" type="text/javascript"></script>
<script src="http://demo.balajeecreation.in/anim-apr14/greenKI-canvasBg/fss.min.js" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" href="http://a.balajeecreation.in/Advertising-Delhi-Css/kitchenindia.css" />
<script src="http://a.balajeecreation.in/Advertising-Delhi-JavaScript/kitchenindia.js" type="text/javascript"></script>
<style>.wrapper{background: none !important; }</style>
-->
</body>
</html>

